// Generated by CoffeeScript 1.10.0
(function() {
  var CHOICES, I18N, IDS, URL, update_count, url;

  I18N = {
    "app": {
      "fr": {
        "explication": "Donner à chaque candidat-e une note allant de 1 (candidat dont on ne veut surtout pas) à 11 (candidat préféré). Chaque note ne doit être attribuée qu'une fois"
      },
      "re": {
        "explication": "Oté ! Donn lo kandida lo poin 1 (kandida sa lé mol) ziska 11 (kandida sa lé gadiamb). insel note insel foi !"
      },
      "uk": {
        "explication": "Donner à chaque candidat-e une note allant de 1 (candidat dont on ne veut surtout pas) à 11 (candidat préféré). Chaque note ne doit être attribuée qu'une fois"
      }
    },
    "qsort": {
      "fr": {
        1: "Nathalie Arthaud",
        2: "François Asselineau",
        3: "Jacques Cheminade",
        4: "Nicolas Dupont-Aignan",
        5: "François Fillon",
        6: "Benoît Hamon",
        7: "Jean Lassalle",
        8: "Marine Le Pen",
        9: "Emmanuel Macron",
        10: "Jean-Luc Mélenchon",
        11: "Philippe Poutou"
      },
      "re": {
        1: "Nathalie Arthaud",
        2: "François Asselineau",
        3: "Jacques Cheminade",
        4: "Nicolas Dupont-Aignan",
        5: "François Fillon",
        6: "Benoît Hamon",
        7: "Jean Lassalle",
        8: "Marine Le Pen",
        9: "Emmanuel Macron",
        10: "Jean-Luc Mélenchon",
        11: "Philippe Poutou"
      },
      "uk": {
        1: "Nathalie Arthaud",
        2: "François Asselineau",
        3: "Jacques Cheminade",
        4: "Nicolas Dupont-Aignan",
        5: "François Fillon",
        6: "Benoît Hamon",
        7: "Jean Lassalle",
        8: "Marine Le Pen",
        9: "Emmanuel Macron",
        10: "Jean-Luc Mélenchon",
        11: "Philippe Poutou"
      }
    }
  };

  CHOICES = 11;

  IDS = [0, 1230461260, 657859686, 112920957, 847960702, 2137008777, 1089137606, 470126607, 1505200759, 1375971800, 844555006, 855634272];

  URL = "https://docs.google.com/forms/d/e/1FAIpQLSd-W4TlNjbg7n9KtQU09RiEpKz2kZI4qJpDwI3RjMMOQqKKgA/viewform?";

  url = "";

  update_count = function() {
    var i;
    if ($("#container li").length === CHOICES) {
      i = 0;
      url = URL;
      $(".candidat").each(function() {
        return url += "entry." + ($(this).attr('data-id')) + "=" + (CHOICES - i++) + "&";
      });
      return $("#origin").before("<button id='go' data-url='" + url + "'>Go</button>");
    } else {
      return $("#go").remove();
    }
  };

  $(function() {
    var set_language;
    set_language = function(lang) {
      var app, html, i, j, qsort, ref;
      $("#container, #origin").empty();
      qsort = I18N["qsort"][lang];
      app = I18N["app"][lang];
      $(".explanation").html(app["explication"]).dialog();
      for (i = j = 1, ref = CHOICES; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
        $("#origin").append("<li class='ui-state-default candidat' data-id='" + IDS[i] + "'>" + qsort[i] + "</li>");
      }
      html = "<p class='caption'><h1>Classement :</h1><ul id='destination' class='connectedSortable destination'></ul></p>";
      $("#container").append(html);
      $("#langage").selectmenu().on("selectmenuchange", function() {
        lang = $(this).val();
        return set_language(lang);
      });
      $(".connectedSortable").sortable({
        connectWith: ".connectedSortable",
        placeholder: "pholder",
        dropOnEmpty: true
      }).disableSelection();
      $("#origin").sortable({
        receive: function(event, ui) {
          return update_count();
        }
      });
      return $("#destination").sortable({
        receive: function(event, ui) {
          return update_count();
        },
        stop: function(event, ui) {
          return update_count();
        }
      });
    };
    set_language("fr");
    $("body").on("click", "#go", function() {
      return window.location.href = url;
    });
    return $("body").on("click", ".question", function() {
      return $(".explanation").dialog("open");
    });
  });

}).call(this);
