// Generated by CoffeeScript 1.9.0
(function() {
  var CHOICES, I18N, IDS, URL, update_count, url;

  I18N = {
    "app": {
      "fr": {
        "explication": "Le but de ce questionnaire n’est pas de rechercher une bonne réponse mais de vous permettre d’identifier votre attitude ainsi que des autres camarades et m’aider à mieux vous connaître et m’adapter à votre situation. Faites glisser les différentes phrases dans les cases correspondantes.",
        "Les 2 plus": "Les 2 qui me correspondent le plus",
        "Les 2 peu": "Les 2 qui me correspondent peu",
        "Les 2 sans opinion": "Les 2 pour lesquelles je n’ai pas d’opinion",
        "Les 2 pas trop": "Les 2 qui me correspondent pas trop",
        "les 2 pas du tout": "Les 2 qui me correspondent pas du tout"
      },
      "re": {
        "explication": "té lé difficil pou espliké !",
        "Les 2 plus": "bann 2 le plus",
        "Les 2 peu": "bann 2 inn bout",
        "Les 2 sans opinion": "bann 2 pa la ek sa !",
        "Les 2 pas trop": "bann 2 pa trotro",
        "les 2 pas du tout": "bann 2 pa di tou"
      },
      "uk": {
        "explication": "The purpose of this questionnaire is not to find a good answer but to help you identify your attitude as well as other friends and help me get to know you and adapt to your situation. Drag the sentences in the corresponding frames.",
        "Les 2 plus": "The 2 that correspond the most to me",
        "Les 2 peu": "The 2 corresponding a bit to me",
        "Les 2 sans opinion": "The 2 whom I do not have an opinion",
        "Les 2 pas trop": "The 2 who do not fit me too",
        "les 2 pas du tout": "The 2 that do not correspond to me at all"
      }
    },
    "qsort": {
      "fr": {
        1: "Arthaud",
        2: "Dupont-Aignan",
        3: "Le Pen",
        4: "Asselineau",
        5: "Fillon",
        6: "Mélenchon",
        7: "Lassalle",
        8: "Cheminade",
        9: "Macron",
        10: "Hamon"
      },
      "re": {
        1: "Arthaud",
        2: "Dupont-Aignan",
        3: "Le Pen",
        4: "Asselineau",
        5: "Fillon",
        6: "Mélenchon",
        7: "Lassalle",
        8: "Cheminade",
        9: "Macron",
        10: "Hamon"
      },
      "uk": {
        1: "Arthaud",
        2: "Dupont-Aignan",
        3: "Le Pen",
        4: "Asselineau",
        5: "Fillon",
        6: "Mélenchon",
        7: "Lassalle",
        8: "Cheminade",
        9: "Macron",
        10: "Hamon"
      }
    }
  };

  CHOICES = 10;

  IDS = [1911008042, 2060227356, 1552551457, 441796097, 1823859130, 1887310124, 377892327, 945229228, 1764134384, 1332486413];

  URL = "https://docs.google.com/forms/d/1oXe3VZp31tv28lsCEEQEGynQKHHbHHcqGRyWEfC_FV4/viewform?";

  url = "";

  update_count = function() {
    var i;
    $(".connectedSortable").each(function() {
      return $(this).prevAll("p.caption:first").find(".count").html($(this).children().length);
    });
    if ($("#container li").length === CHOICES) {
      i = 0;
      url = URL;
      $("#2 li").each(function() {
        return url += "entry." + IDS[i++] + "=" + ($(this).attr('data-item')) + "&";
      });
      $("#1 li").each(function() {
        return url += "entry." + IDS[i++] + "=" + ($(this).attr('data-item')) + "&";
      });
      $("#0 li").each(function() {
        return url += "entry." + IDS[i++] + "=" + ($(this).attr('data-item')) + "&";
      });
      $("#-1 li").each(function() {
        return url += "entry." + IDS[i++] + "=" + ($(this).attr('data-item')) + "&";
      });
      $("#-2 li").each(function() {
        return url += "entry." + IDS[i++] + "=" + ($(this).attr('data-item')) + "&";
      });
      return $("#origin").before("<button id='go' data-url='" + url + "'>Go</button>");
    } else {
      return $("#go").remove();
    }
  };

  $(function() {
    var set_language;
    set_language = function(lang) {
      var app, c, html, i, n, qsort, t, _i, _j;
      $("#container, #origin").empty();
      qsort = I18N["qsort"][lang];
      app = I18N["app"][lang];
      $(".explanation").html(app["explication"]).dialog();
      for (i = _i = 1; 1 <= CHOICES ? _i <= CHOICES : _i >= CHOICES; i = 1 <= CHOICES ? ++_i : --_i) {
        $("#origin").append("<li class='ui-state-default' data-item='" + i + "'>" + qsort[i] + "</li>");
      }
      c = [2, 1, 0, -1, -2];
      n = [2, 2, 2, 2, 2];
      t = [app["Les 2 plus"], app["Les 2 peu"], app["Les 2 sans opinion"], app["Les 2 pas trop"], app["les 2 pas du tout"]];
      for (i = _j = 0; _j <= 4; i = ++_j) {
        html = "<p class='caption'>" + t[i] + " (<span class='count'>0</span>/" + n[i] + ")</p><ul id='" + c[i] + "' class='connectedSortable destination' data-coeff='" + c[i] + "' data-max='" + n[i] + "'></ul>";
        $("#container").append(html);
      }
      $("#langage").selectmenu().on("selectmenuchange", function() {
        lang = $(this).val();
        return set_language(lang);
      });
      $(".connectedSortable").sortable({
        connectWith: ".connectedSortable",
        placeholder: "pholder",
        dropOnEmpty: true
      }).disableSelection();
      $("#origin").sortable({
        receive: function(event, ui) {
          return update_count();
        }
      });
      return $(".destination").sortable({
        receive: function(event, ui) {
          var m;
          m = parseInt($(this).attr("data-max"));
          if ($(this).children().length > m) {
            alert("Attention " + m + " max ! Liberez en un avant !");
            $(ui.sender).sortable('cancel');
          }
          return update_count();
        }
      });
    };
    set_language("fr");
    $("body").on("click", "#go", function() {
      return window.location.href = url;
    });
    return $("body").on("click", ".question", function() {
      return $(".explanation").dialog("open");
    });
  });

}).call(this);
